---
- name: Install kubelet kubeadm kubectl
  hosts: k8s_master, k8s_master2
  become: yes
  gather_facts: no

  vars_files:
    - vm_vars.yml
  
  roles:
    - kub_install
    - reboot_wait
    - set_hosts