---
##
# Start VM
# 
##

- name: Start VM
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_host }}"
    name: "{{ item.name }}"
    node: "{{ proxmox_node }}"
    state: started
  with_items: "{{ vms }}"