---
##
# Stop VM
# 
##

- name: Stop VMs
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_host }}"
    name: "{{ item.name }}"
    node: "{{ proxmox_node }}"
    state: stopped
    force: true
  with_items: "{{ vms }}"