---
##
# Delete VM
# 
##

- name: Delete all VMs
  community.general.proxmox_kvm:
    api_user: root@pam
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_host }}"
    name: "{{ item.name }}"
    node: "{{ proxmox_node }}"
    state: absent
  with_items: "{{ vms }}"